# Generated by Django 3.0.8 on 2020-07-23 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='descriptiom',
            new_name='description',
        ),
    ]
