# Generated by Django 3.0.8 on 2020-07-23 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_auto_20200723_1415'),
    ]

    operations = [
        migrations.RenameField(
            model_name='journalist',
            old_name='biograpth',
            new_name='biography',
        ),
    ]
